name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # This allows manual triggering

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set Go import path
      run: go env -w GO111MODULE=on

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: make style test

    - name: Verify front-end is up to date
      run: |
        make clean assets
        make mod-tidy
        # git diff --exit-code
